[package]
name = "mux-runtime"
version = "0.1.0"
edition = "2024"

[lib]
name = "mux_runtime"
crate-type = ["rlib"]

[dependencies]
gc = { version = "0.4", default-features = false }
ordered-float = { version = "4.0", default-features = false }
